# Generated by Django 5.0.6 on 2024-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_api', '0006_alter_task_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[(1, 'Nova'), (2, 'Em Andamento'), (3, 'Concluida'), (4, 'Cancelada')], max_length=1),
        ),
    ]
